FROM mcr.microsoft.com/windows/servercore:ltsc2022

WORKDIR C:/app
COPY . .
CMD ["powershell.exe"]

# This Dockerfile creates a Windows-based container using the Server Core image.
# It sets the working directory to C:/app and copies the current directory's contents into the container.
# This Dockerfile is for creating a Windows-based container using PowerShell.
# It uses the Windows Server Core image as the base image.